global using AdventOfCode.Tools;
global using AdventOfCode.Tools.Extensions;
global using System.Numerics;
global using System.Text.RegularExpressions;
global using System.Globalization;
global using System.Text;
global using AdventOfCode.Maps;
using AdventOfCode.Solutions2015;
using AdventOfCode.Solutions2016;
using AdventOfCode.Solutions2017;
using AdventOfCode.Solutions2018;
using AdventOfCode.Solutions2019;
using AdventOfCode.Solutions2020;
using AdventOfCode.Solutions2021;
using AdventOfCode.Solutions2022;
using AdventOfCode.Solutions2023;
using AdventOfCode.Solutions2024;
using AdventOfCode.Solutions2025;
using AdventOfCode.Solutions9999;

new Year().Run(true);
new Year2015().Run();
new Year2016().Run(true);
new Year2017().Run(true);
new Year2018().Run(true);
new Year2019().Run(true);
new Year2020().Run(true);
new Year2021().Run(true);
new Year2022().Run(true);
new Year2023().Run(true);
new Year2024().Run(true);
new Year2025().Run(true);